import type { ConfigField } from "./types.ts";

export const OPERATIONAL_DEFAULTS = {
  settlementReconcileIntervalMs: 15_000,
  settlementReconcileBatchSizeCount: 20,
  settlementReconcileInitialDelayMs: 3_000,
  providerHttpTimeoutMs: 120_000,
  catalogCacheTtlMs: 600_000,
  workerConcurrencyCount: 1,
  shutdownTimeoutMs: 10_000,
} as const;

export const MIN_JWT_SECRET_LEN = 32;

function defineField(field: ConfigField): ConfigField {
  return field;
}

export const CONFIG_FIELDS: readonly ConfigField[] = [
  defineField({
    key: "DOMAIN",
    kind: "domain",
    scope: "deploy",
    required: true,
    yamlPath: "domain",
    description: "Public hostname for the panel and TLS certificate.",
  }),
  defineField({
    key: "ADMIN_EMAIL",
    kind: "email",
    scope: "deploy",
    required: true,
    yamlPath: "adminEmail",
    description: "Let's Encrypt and admin contact email.",
  }),
  defineField({
    key: "MONGO_USER",
    kind: "string",
    scope: "deploy",
    required: true,
    yamlPath: "database.user",
    description: "MongoDB root username.",
  }),
  defineField({
    key: "MONGO_PASS",
    kind: "secret",
    scope: "deploy",
    required: true,
    secret: true,
    yamlPath: "database.password",
    description: "MongoDB root password.",
  }),
  defineField({
    key: "MONGO_USER_URI",
    kind: "string",
    scope: "deploy",
    required: false,
    derived: true,
    description: "Percent-encoded MONGO_USER for mongodb:// URIs.",
  }),
  defineField({
    key: "MONGO_PASS_URI",
    kind: "secret",
    scope: "deploy",
    required: false,
    derived: true,
    secret: true,
    description: "Percent-encoded MONGO_PASS for mongodb:// URIs.",
  }),
  defineField({
    key: "MONGODB_DB",
    kind: "mongoDbName",
    scope: "shared",
    required: false,
    default: "tokenpanel",
    yamlPath: "database.name",
    description: "MongoDB database name.",
    validation: { maxLength: 63, pattern: "^[A-Za-z0-9_-]+$" },
  }),
  defineField({
    key: "MONGODB_URI",
    kind: "mongoUri",
    scope: "api",
    required: false,
    derived: true,
    yamlPath: "database.uri",
    description: "MongoDB connection URI. Generated from database settings unless overridden.",
  }),
  defineField({
    key: "USE_CADDY",
    kind: "boolean",
    scope: "deploy",
    required: false,
    default: "y",
    booleanFormat: "yn",
    yamlPath: "proxy.caddy",
    description: "Run the built-in Caddy TLS proxy.",
  }),
  defineField({
    key: "API_PORT",
    kind: "integer",
    scope: "deploy",
    required: false,
    default: 3000,
    yamlPath: "proxy.apiPort",
    description: "Host port published when Caddy is disabled.",
    validation: { min: 1, max: 65535 },
  }),
  defineField({
    key: "TZ",
    kind: "timezone",
    scope: "deploy",
    required: false,
    default: "UTC",
    yamlPath: "timezone",
    description: "Container timezone.",
  }),
  defineField({
    key: "NODE_ENV",
    kind: "environment",
    scope: "api",
    required: false,
    default: "production",
    yamlPath: "api.environment",
    description: "Runtime environment.",
    validation: { choices: ["development", "test", "production"] },
  }),
  defineField({
    key: "PORT",
    kind: "integer",
    scope: "api",
    required: false,
    default: 3000,
    yamlPath: "api.port",
    description: "In-container API port.",
    validation: { min: 1, max: 65535 },
  }),
  defineField({
    key: "JWT_SECRET",
    kind: "secret",
    scope: "api",
    required: true,
    secret: true,
    yamlPath: "api.jwtSecret",
    description: "JWT signing and provider-credential encryption secret.",
    validation: { minLength: MIN_JWT_SECRET_LEN },
  }),
  defineField({
    key: "ALLOW_WEAK_JWT_SECRET",
    kind: "boolean",
    scope: "api",
    required: false,
    default: false,
    booleanFormat: "trueFalse",
    yamlPath: "api.allowWeakJwtSecret",
    description: "Test-only bypass for the JWT secret length minimum.",
  }),
  defineField({
    key: "CORS_ORIGINS",
    kind: "originList",
    scope: "api",
    required: false,
    default: [],
    yamlPath: "api.corsOrigins",
    description: "Allowed browser origins for CORS.",
  }),
  defineField({
    key: "TRUST_PROXY",
    kind: "boolean",
    scope: "shared",
    required: false,
    booleanFormat: "trueFalse",
    yamlPath: "proxy.trustProxy",
    description: "Resolve client IP from reverse-proxy headers.",
  }),
  defineField({
    key: "TRUST_CLOUDFLARE",
    kind: "boolean",
    scope: "shared",
    required: false,
    default: false,
    booleanFormat: "trueFalse",
    yamlPath: "proxy.trustCloudflare",
    description: "Trust CF-Connecting-IP from Cloudflare edge IPs.",
  }),
  defineField({
    key: "TRUSTED_PROXIES",
    kind: "proxyList",
    scope: "shared",
    required: false,
    default: [],
    yamlPath: "proxy.trustedProxies",
    description: "Proxy IPs or CIDRs allowed to set client-IP headers.",
  }),
  defineField({
    key: "SMTP_HOST",
    kind: "string",
    scope: "deploy",
    required: false,
    yamlPath: "smtp.host",
    description: "SMTP host for outbound mail.",
  }),
  defineField({
    key: "SMTP_PORT",
    kind: "integer",
    scope: "deploy",
    required: false,
    yamlPath: "smtp.port",
    description: "SMTP port.",
    validation: { min: 1, max: 65535 },
  }),
  defineField({
    key: "SMTP_USER",
    kind: "string",
    scope: "deploy",
    required: false,
    yamlPath: "smtp.user",
    description: "SMTP username.",
  }),
  defineField({
    key: "SMTP_PASS",
    kind: "secret",
    scope: "deploy",
    required: false,
    secret: true,
    yamlPath: "smtp.pass",
    description: "SMTP password.",
  }),
  defineField({
    key: "SMTP_FROM",
    kind: "string",
    scope: "deploy",
    required: false,
    yamlPath: "smtp.from",
    description: "SMTP sender address.",
  }),
  defineField({
    key: "CSP_CONNECT_SRC",
    kind: "stringList",
    scope: "deploy",
    required: false,
    yamlPath: "csp.connectSrc",
    description: "Extra CSP connect-src origins for split-origin admin.",
  }),
  defineField({
    key: "SETTLEMENT_RECONCILE_INTERVAL_MS",
    kind: "integer",
    scope: "api",
    required: false,
    default: OPERATIONAL_DEFAULTS.settlementReconcileIntervalMs,
    runtimeKey: "settlementReconcileIntervalMs",
    yamlPath: "api.operational.settlementReconcileIntervalMs",
    description: "Settlement outbox reconcile poll interval.",
    validation: { min: 0, max: 86_400_000 },
  }),
  defineField({
    key: "SETTLEMENT_RECONCILE_BATCH_SIZE",
    kind: "integer",
    scope: "api",
    required: false,
    default: OPERATIONAL_DEFAULTS.settlementReconcileBatchSizeCount,
    runtimeKey: "settlementReconcileBatchSizeCount",
    yamlPath: "api.operational.settlementReconcileBatchSizeCount",
    description: "Max outbox rows claimed per reconcile tick.",
    validation: { min: 1, max: 10_000 },
  }),
  defineField({
    key: "SETTLEMENT_RECONCILE_INITIAL_DELAY_MS",
    kind: "integer",
    scope: "api",
    required: false,
    default: OPERATIONAL_DEFAULTS.settlementReconcileInitialDelayMs,
    runtimeKey: "settlementReconcileInitialDelayMs",
    yamlPath: "api.operational.settlementReconcileInitialDelayMs",
    description: "Delay before first reconcile tick.",
    validation: { min: 0, max: 86_400_000 },
  }),
  defineField({
    key: "PROVIDER_HTTP_TIMEOUT_MS",
    kind: "integer",
    scope: "api",
    required: false,
    default: OPERATIONAL_DEFAULTS.providerHttpTimeoutMs,
    runtimeKey: "providerHttpTimeoutMs",
    yamlPath: "api.operational.providerHttpTimeoutMs",
    description: "Global upstream provider HTTP timeout.",
    validation: { min: 0, max: 3_600_000 },
  }),
  defineField({
    key: "CATALOG_CACHE_TTL_MS",
    kind: "integer",
    scope: "api",
    required: false,
    default: OPERATIONAL_DEFAULTS.catalogCacheTtlMs,
    runtimeKey: "catalogCacheTtlMs",
    yamlPath: "api.operational.catalogCacheTtlMs",
    description: "Catalog-source response cache TTL.",
    validation: { min: 0, max: 86_400_000 },
  }),
  defineField({
    key: "WORKER_CONCURRENCY",
    kind: "integer",
    scope: "api",
    required: false,
    default: OPERATIONAL_DEFAULTS.workerConcurrencyCount,
    runtimeKey: "workerConcurrencyCount",
    yamlPath: "api.operational.workerConcurrencyCount",
    description: "Concurrent reconcile row handlers.",
    validation: { min: 1, max: 256 },
  }),
  defineField({
    key: "SHUTDOWN_TIMEOUT_MS",
    kind: "integer",
    scope: "api",
    required: false,
    default: OPERATIONAL_DEFAULTS.shutdownTimeoutMs,
    runtimeKey: "shutdownTimeoutMs",
    yamlPath: "api.operational.shutdownTimeoutMs",
    description: "Graceful shutdown budget.",
    validation: { min: 0, max: 600_000 },
  }),
];

export function fieldByKey(key: string): ConfigField | undefined {
  return CONFIG_FIELDS.find((field) => field.key === key);
}

export function fieldsByScope(scope: ConfigField["scope"]): readonly ConfigField[] {
  return CONFIG_FIELDS.filter((field) => field.scope === scope);
}
